import { yamahaMG16XU } from '../data/mixerDefinitions'
import type { StagePlotProject } from '../types'

const rhythmGuitarist1Id = 'pf-el-rhythm-gtr-1'
const rhythmGuitarist2Id = 'pf-el-rhythm-gtr-2'
const drumsId = 'pf-el-drums'
const harmonicaId = 'pf-el-harmonica'
const leadGuitaristId = 'pf-el-lead-gtr'
const bassistId = 'pf-el-bassist'
const keyboardistId = 'pf-el-keys'
const lapSteelId = 'pf-el-lap-steel'

/**
 * Binghamton Porchfest — ~8 performers split across porch/driveway/lawn.
 * The mixer sits on the grass, separated from the porch by landscaping,
 * which is exactly why the canvas represents the whole layout area rather
 * than just a stage riser.
 */
export const porchfestProject: StagePlotProject = {
  id: 'seed-porchfest',
  name: 'Binghamton Porchfest',
  venue: 'Porchfest — front porch/driveway/lawn',
  showDate: '',
  contactInfo: '',
  stageWidthFt: 45,
  stageDepthFt: 35,
  mixerDefinitionId: yamahaMG16XU.id,
  auxAssignments: [
    { auxId: 'aux1', label: 'Wedge Mix A' },
    { auxId: 'aux2', label: 'Wedge Mix B' },
    { auxId: 'aux3', label: 'AUX3' },
    { auxId: 'aux4', label: 'AUX4 / FX' },
  ],
  switchablePortModes: [],
  elements: [
    {
      id: rhythmGuitarist1Id,
      type: 'musician',
      label: 'Rhythm Guitar 1',
      xFt: 4,
      yFt: 5,
      widthFt: 2,
      depthFt: 2,
      rotationDeg: 0,
      status: 'confirmed',
      linkedChannelId: 'pf-ch-acoustic-gtr',
    },
    {
      id: rhythmGuitarist2Id,
      type: 'musician',
      label: 'Rhythm Guitar 2 / Vox',
      xFt: 8,
      yFt: 5,
      widthFt: 2,
      depthFt: 2,
      rotationDeg: 0,
      status: 'confirmed',
      linkedChannelId: 'pf-ch-rhythm-gtr-2',
    },
    {
      id: drumsId,
      type: 'drumKit',
      label: 'Drums',
      xFt: 13,
      yFt: 6,
      widthFt: 6,
      depthFt: 5,
      rotationDeg: 0,
      status: 'confirmed',
      linkedChannelId: 'pf-ch-kick',
    },
    {
      id: harmonicaId,
      type: 'musician',
      label: 'Harmonica (operator)',
      xFt: 1,
      yFt: 5,
      widthFt: 2,
      depthFt: 2,
      rotationDeg: 0,
      status: 'confirmed',
      notes: 'Also running sound from here.',
      linkedChannelId: 'pf-ch-harmonica',
    },
    {
      id: leadGuitaristId,
      type: 'musician',
      label: 'Lead Guitar',
      xFt: 11,
      yFt: 3,
      widthFt: 2,
      depthFt: 2,
      rotationDeg: 0,
      status: 'tentative',
      notes: 'Bailed before the gig — kept on the plot in case plans change again.',
    },
    {
      id: bassistId,
      type: 'musician',
      label: 'Bass',
      xFt: 22,
      yFt: 16,
      widthFt: 2,
      depthFt: 2,
      rotationDeg: 0,
      status: 'confirmed',
      linkedChannelId: 'pf-ch-bass',
    },
    {
      id: keyboardistId,
      type: 'keyboard',
      label: 'Keys',
      xFt: 26,
      yFt: 16,
      widthFt: 4,
      depthFt: 2,
      rotationDeg: 0,
      status: 'confirmed',
      notes: 'Self-contained — not run through the board.',
    },
    {
      id: lapSteelId,
      type: 'musician',
      label: 'Lap Steel',
      xFt: 34,
      yFt: 24,
      widthFt: 2,
      depthFt: 2,
      rotationDeg: 0,
      status: 'confirmed',
      linkedChannelId: 'pf-ch-lap-steel',
    },
    {
      id: 'pf-el-mixer',
      type: 'mixer',
      label: 'Mixer (FOH)',
      xFt: 32,
      yFt: 4,
      widthFt: 3,
      depthFt: 2,
      rotationDeg: 0,
      status: 'confirmed',
      notes: 'On the grass, separated from the porch by landscaping — long cable runs to the porch mics.',
    },
    {
      id: 'pf-el-wedge-1',
      type: 'monitorWedge',
      label: 'Wedge 1',
      xFt: 5,
      yFt: 4,
      widthFt: 2,
      depthFt: 1.5,
      rotationDeg: 180,
      status: 'confirmed',
    },
    {
      id: 'pf-el-wedge-2',
      type: 'monitorWedge',
      label: 'Wedge 2',
      xFt: 9,
      yFt: 4,
      widthFt: 2,
      depthFt: 1.5,
      rotationDeg: 180,
      status: 'tentative',
      notes: "Didn't arrive in time — plan B is sharing Wedge 1.",
    },
    {
      id: 'pf-el-pa-l',
      type: 'paSpeaker',
      label: 'PA Main L',
      xFt: 0,
      yFt: 0,
      widthFt: 1.5,
      depthFt: 1.5,
      rotationDeg: 0,
      status: 'confirmed',
      notes: 'Fed from mixer main out via LINE input.',
    },
    {
      id: 'pf-el-pa-r',
      type: 'paSpeaker',
      label: 'PA Main R',
      xFt: 15,
      yFt: 0,
      widthFt: 1.5,
      depthFt: 1.5,
      rotationDeg: 0,
      status: 'confirmed',
      notes: 'Fed from mixer main out via LINE input.',
    },
  ],
  channels: [
    {
      id: 'pf-ch-acoustic-gtr',
      channelNumber: 1,
      source: 'Acoustic Guitar (Rhythm 1)',
      sourceKind: 'instrumentDirect',
      connectorType: 'TS',
      phantomPower: false,
      status: 'confirmed',
      mixerPortId: 'ch1',
      linkedElementId: rhythmGuitarist1Id,
      auxLevels: [{ auxId: 'aux1', level: 4 }],
    },
    {
      id: 'pf-ch-rhythm-gtr-2',
      channelNumber: 2,
      source: 'Rhythm Guitar 2 (amp, mic’d)',
      sourceKind: 'mic',
      connectorType: 'XLR',
      phantomPower: false,
      status: 'confirmed',
      mixerPortId: 'ch2',
      linkedElementId: rhythmGuitarist2Id,
      auxLevels: [{ auxId: 'aux1', level: 5 }],
    },
    {
      id: 'pf-ch-rhythm-gtr-2-vox',
      channelNumber: 3,
      source: 'Vocal (Rhythm Guitar 2)',
      sourceKind: 'mic',
      connectorType: 'XLR',
      phantomPower: true,
      status: 'confirmed',
      mixerPortId: 'ch3',
      linkedElementId: rhythmGuitarist2Id,
      auxLevels: [{ auxId: 'aux1', level: 6 }, { auxId: 'aux2', level: 6 }],
    },
    {
      id: 'pf-ch-kick',
      channelNumber: 4,
      source: 'Kick',
      sourceKind: 'mic',
      connectorType: 'XLR',
      phantomPower: false,
      status: 'confirmed',
      mixerPortId: 'ch4',
      linkedElementId: drumsId,
      auxLevels: [],
    },
    {
      id: 'pf-ch-snare',
      channelNumber: 5,
      source: 'Snare',
      sourceKind: 'mic',
      connectorType: 'XLR',
      phantomPower: false,
      status: 'confirmed',
      mixerPortId: 'ch5',
      linkedElementId: drumsId,
      auxLevels: [],
    },
    {
      id: 'pf-ch-harmonica',
      channelNumber: 6,
      source: 'Harmonica',
      sourceKind: 'mic',
      connectorType: 'XLR',
      phantomPower: false,
      status: 'confirmed',
      mixerPortId: 'ch6',
      linkedElementId: harmonicaId,
      auxLevels: [{ auxId: 'aux2', level: 5 }],
    },
    {
      id: 'pf-ch-bass',
      channelNumber: 7,
      source: 'Bass',
      sourceKind: 'di',
      connectorType: 'XLR',
      phantomPower: false,
      status: 'confirmed',
      mixerPortId: 'ch7',
      linkedElementId: bassistId,
      auxLevels: [{ auxId: 'aux2', level: 4 }],
    },
    {
      id: 'pf-ch-lap-steel',
      channelNumber: 8,
      source: 'Lap Steel',
      sourceKind: 'mic',
      connectorType: 'XLR',
      intermediateDevice: "Lap steel's own amp, mic'd",
      phantomPower: false,
      status: 'confirmed',
      mixerPortId: 'ch8',
      linkedElementId: lapSteelId,
      auxLevels: [{ auxId: 'aux1', level: 3 }, { auxId: 'aux2', level: 3 }],
    },
  ],
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
}
