import { yamahaMG16XU } from '../data/mixerDefinitions'
import type { StagePlotProject } from '../types'

const acousticGtrVoxId = 'th-el-acoustic-gtr-vox'
const electricRhythmId = 'th-el-electric-rhythm'
const bassistId = 'th-el-bassist'
const leadGuitaristId = 'th-el-lead-gtr'
const harmonicaId = 'th-el-harmonica'
const lapSteelId = 'th-el-lap-steel'
const drummerId = 'th-el-drummer'
const bonesId = 'th-el-bones'

/**
 * Tap House 66 — a bar gig with a full band and one of everything that
 * makes mixer-aware planning worth having: a guitarist who isn't on the
 * board at all, a drummer routed through her own bass amp's line out, and
 * (if the optional bones player shows) more mic sources than mono inputs
 * once the switchable pairs are already committed elsewhere — which is
 * exactly the kind of thing validateProject() should catch, not hide.
 */
export const tapHouse66Project: StagePlotProject = {
  id: 'seed-tap-house-66',
  name: 'Tap House 66',
  venue: 'Tap House 66',
  showDate: '',
  contactInfo: '',
  stageWidthFt: 18,
  stageDepthFt: 14,
  mixerDefinitionId: yamahaMG16XU.id,
  auxAssignments: [
    { auxId: 'aux1', label: 'Drummer wedge' },
    { auxId: 'aux2', label: 'Lead vocal wedge', prePost: 'pre' },
    { auxId: 'aux3', label: 'Backup vocals wedge' },
    { auxId: 'aux4', label: 'Guitars wedge' },
  ],
  switchablePortModes: [
    { portId: 'ch9_10', mode: 'stereo' },
    { portId: 'ch11_12', mode: 'mono' },
  ],
  elements: [
    {
      id: acousticGtrVoxId,
      type: 'musician',
      label: 'Acoustic Guitar / Lead Vox',
      xFt: 4,
      yFt: 3,
      widthFt: 2,
      depthFt: 2,
      rotationDeg: 0,
      status: 'confirmed',
      linkedChannelId: 'th-ch-acoustic-gtr',
    },
    {
      id: electricRhythmId,
      type: 'musician',
      label: 'Electric Rhythm / Backup Vox',
      xFt: 7,
      yFt: 3,
      widthFt: 2,
      depthFt: 2,
      rotationDeg: 0,
      status: 'confirmed',
      notes: 'Active pickups.',
      linkedChannelId: 'th-ch-electric-rhythm',
    },
    {
      id: bassistId,
      type: 'musician',
      label: 'Bass / Backup Vox',
      xFt: 10,
      yFt: 3,
      widthFt: 2,
      depthFt: 2,
      rotationDeg: 0,
      status: 'confirmed',
      linkedChannelId: 'th-ch-bass',
    },
    {
      id: leadGuitaristId,
      type: 'musician',
      label: 'Lead Guitar',
      xFt: 13,
      yFt: 3,
      widthFt: 2,
      depthFt: 2,
      rotationDeg: 0,
      status: 'confirmed',
      notes: "Runs only into his own amp — not on the board at all.",
    },
    {
      id: harmonicaId,
      type: 'musician',
      label: 'Harmonica (operator)',
      xFt: 2,
      yFt: 5,
      widthFt: 2,
      depthFt: 2,
      rotationDeg: 0,
      status: 'confirmed',
      linkedChannelId: 'th-ch-harmonica',
    },
    {
      id: lapSteelId,
      type: 'musician',
      label: 'Lap Steel',
      xFt: 15,
      yFt: 5,
      widthFt: 2,
      depthFt: 2,
      rotationDeg: 0,
      status: 'confirmed',
      linkedChannelId: 'th-ch-lap-steel',
    },
    {
      id: drummerId,
      type: 'drumKit',
      label: 'Drums / Backup Vox',
      xFt: 9,
      yFt: 8,
      widthFt: 6,
      depthFt: 5,
      rotationDeg: 0,
      status: 'confirmed',
      notes: "Kit runs through her own Fender Rumble 40 bass amp and out that amp's XLR line output.",
      linkedChannelId: 'th-ch-drummer-kit',
    },
    {
      id: bonesId,
      type: 'musician',
      label: 'Bones (optional)',
      xFt: 16,
      yFt: 7,
      widthFt: 2,
      depthFt: 2,
      rotationDeg: 0,
      status: 'tentative',
      notes: 'Depends who shows up — not confirmed.',
      linkedChannelId: 'th-ch-bones',
    },
    {
      id: 'th-el-mixer',
      type: 'mixer',
      label: 'Mixer (FOH)',
      xFt: 1,
      yFt: 10,
      widthFt: 3,
      depthFt: 2,
      rotationDeg: 0,
      status: 'confirmed',
    },
    { id: 'th-el-wedge-1', type: 'monitorWedge', label: 'Wedge 1 (Drummer)', xFt: 9, yFt: 6.5, widthFt: 2, depthFt: 1.5, rotationDeg: 0, status: 'confirmed', notes: 'Fed by AUX1.' },
    { id: 'th-el-wedge-2', type: 'monitorWedge', label: 'Wedge 2 (Lead vox)', xFt: 4, yFt: 2, widthFt: 2, depthFt: 1.5, rotationDeg: 0, status: 'confirmed', notes: 'Fed by AUX2.' },
    { id: 'th-el-wedge-3', type: 'monitorWedge', label: 'Wedge 3 (Backup vox)', xFt: 10, yFt: 2, widthFt: 2, depthFt: 1.5, rotationDeg: 0, status: 'confirmed', notes: 'Fed by AUX3.' },
    { id: 'th-el-wedge-4', type: 'monitorWedge', label: 'Wedge 4 (Guitars)', xFt: 13, yFt: 2, widthFt: 2, depthFt: 1.5, rotationDeg: 0, status: 'confirmed', notes: 'Fed by AUX4.' },
  ],
  channels: [
    {
      id: 'th-ch-acoustic-gtr',
      channelNumber: 1,
      source: 'Acoustic Guitar',
      sourceKind: 'instrumentDirect',
      connectorType: 'TS',
      phantomPower: false,
      status: 'confirmed',
      mixerPortId: 'ch1',
      linkedElementId: acousticGtrVoxId,
      auxLevels: [{ auxId: 'aux4', level: 5 }],
    },
    {
      id: 'th-ch-lead-vox',
      channelNumber: 2,
      source: 'Lead Vocal',
      sourceKind: 'mic',
      connectorType: 'XLR',
      phantomPower: true,
      status: 'confirmed',
      mixerPortId: 'ch2',
      linkedElementId: acousticGtrVoxId,
      auxLevels: [{ auxId: 'aux2', level: 7 }],
    },
    {
      id: 'th-ch-electric-rhythm',
      channelNumber: 3,
      source: 'Electric Rhythm Guitar',
      sourceKind: 'instrumentDirect',
      connectorType: 'TS',
      notes: 'Active pickups — direct into Hi-Z input.',
      phantomPower: false,
      status: 'confirmed',
      mixerPortId: 'ch3',
      linkedElementId: electricRhythmId,
      auxLevels: [{ auxId: 'aux4', level: 5 }],
    },
    {
      id: 'th-ch-backup-vox-1',
      channelNumber: 4,
      source: 'Backup Vocal (Rhythm Guitar)',
      sourceKind: 'mic',
      connectorType: 'XLR',
      phantomPower: true,
      status: 'confirmed',
      mixerPortId: 'ch4',
      linkedElementId: electricRhythmId,
      auxLevels: [{ auxId: 'aux3', level: 6 }],
    },
    {
      id: 'th-ch-bass',
      channelNumber: 5,
      source: 'Bass',
      sourceKind: 'di',
      connectorType: 'XLR',
      notes: 'Amp vs. DI still an open question — confirm before load-in.',
      phantomPower: false,
      status: 'confirmed',
      mixerPortId: 'ch5',
      linkedElementId: bassistId,
      auxLevels: [{ auxId: 'aux1', level: 4 }],
    },
    {
      id: 'th-ch-backup-vox-2',
      channelNumber: 6,
      source: 'Backup Vocal (Bass)',
      sourceKind: 'mic',
      connectorType: 'XLR',
      phantomPower: true,
      status: 'confirmed',
      mixerPortId: 'ch6',
      linkedElementId: bassistId,
      auxLevels: [{ auxId: 'aux3', level: 6 }],
    },
    {
      id: 'th-ch-harmonica',
      channelNumber: 7,
      source: 'Harmonica',
      sourceKind: 'mic',
      connectorType: 'XLR',
      phantomPower: false,
      status: 'confirmed',
      mixerPortId: 'ch7',
      linkedElementId: harmonicaId,
      auxLevels: [{ auxId: 'aux4', level: 4 }],
    },
    {
      id: 'th-ch-lap-steel',
      channelNumber: 8,
      source: 'Lap Steel',
      sourceKind: 'mic',
      connectorType: 'XLR',
      intermediateDevice: "Lap steel's own amp, mic'd",
      phantomPower: false,
      status: 'confirmed',
      mixerPortId: 'ch8',
      linkedElementId: lapSteelId,
      auxLevels: [{ auxId: 'aux4', level: 4 }],
    },
    {
      id: 'th-ch-drummer-kit',
      channelNumber: 9,
      source: 'Drum Kit (via bass amp)',
      sourceKind: 'lineFromDevice',
      connectorType: 'TRS',
      intermediateDevice: 'Fender Rumble 40 amp, XLR line out',
      notes: 'Amp’s XLR line out adapted to TRS for CH9/10 in stereo-line mode.',
      phantomPower: false,
      status: 'confirmed',
      mixerPortId: 'ch9_10',
      linkedElementId: drummerId,
      auxLevels: [],
    },
    {
      id: 'th-ch-backup-vox-3',
      channelNumber: 11,
      source: 'Backup Vocal (Drums)',
      sourceKind: 'mic',
      connectorType: 'XLR',
      phantomPower: true,
      status: 'confirmed',
      mixerPortId: 'ch11_12',
      linkedElementId: drummerId,
      auxLevels: [{ auxId: 'aux3', level: 5 }],
    },
    {
      id: 'th-ch-bones',
      channelNumber: 12,
      source: 'Bones',
      sourceKind: 'mic',
      connectorType: 'XLR',
      notes: 'Optional — depends who shows. No mono mic slot free if he does; see input-list warning.',
      phantomPower: false,
      status: 'tentative',
      linkedElementId: bonesId,
      auxLevels: [],
    },
  ],
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
}
